### ISSUE TITLE
Broken link on doc site

### ISSUE THREAD

**Issue by riziles** [360-info/sverto#13]
First of all, this is awesome!

Second, there is a broken link on the doc site. I believe this hyperlink:

https://github.com/360-info/sverto/blob/35b46f338429eb38582ebf1aee03c590db187932/docs/index.qmd#L71

should point to:

https://github.com/360-info/sverto/blob/main/example.qmd

**Comment by jimjam-slam** [comment]
Thanks for the catch @riziles! I'll update it ASAP!
